### ISSUE TITLE
hw.txt 파일관련 매우매우 중요한 이슈 꼭봐주세요 제발 부탁입니다

### ISSUE THREAD

**Issue by ByeongWOo2** [yiseoffline/open-source-1#10]
intj는 어떤 유형인가요

**Comment by yiseoffline** [comment]
음.. 일단 intj는 흠.. 저도 intj가 된지 얼마 안돼서 잘 모루겠네요? 
네이버에 검색해보시는걸 ㅊㅊ드립ㄴ디아
그리고 깃허브가 어려운 이유는 바로
'다 영어기 때문!!!!!!!!!!!!!' intj는 영어를 싫어합니닷
